const aboutStyleClasses = {
    aboutUsContainer:`
        block
        p-100
        mt-25000
        mb-5
    `,
    aboutUsGrid:`
        gap-6
        grid
        mb-6
        mx-auto
        md:grid-cols-2
        sm:grid-cols-none
        text-center
        mt-15
    `,
    contributorGrid:`
        gap-6
        grid
        mb-6
        mx-auto
        md:grid-cols-4
        sm:grid-cols-none
        text-center
        mt-15
    `,
    hyperlinks:`
        text-blue-500
        hover:text-blue-700
        underline
`,
}